[project]
name = "task-tracker"
version = "0.1.0"
description = "Simple python Task tracker on the CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
